import {
  CASE_GRAPH_SCHEMA_VERSION,
  CASE_GRAPH_VERSION,
  parseCaseGraphV1,
  type CaseGraphV1,
  type Provenance,
} from "./schema";

const sourceProvenance = (
  provenanceId: string,
  sourceSegmentIds: string[],
  note: string,
  confidence = 1,
): Provenance => ({
  provenanceId,
  kind: "source",
  sourceSegmentIds,
  note,
  confidence,
});

const authoringProvenance = (provenanceId: string, note: string): Provenance => ({
  provenanceId,
  kind: "authoring",
  sourceSegmentIds: [],
  note,
  confidence: 1,
});

const rawThreeWitnessFixture = {
  schemaVersion: CASE_GRAPH_SCHEMA_VERSION,
  caseId: "case_redwood_signal_v1",
  version: CASE_GRAPH_VERSION,
  title: "Rina Shah v. Redwood Signal Systems",
  summary:
    "A fictional retaliation dispute about whether a safety complaint influenced a product engineer's termination.",
  status: "published",
  educationalDisclaimer:
    "Fictional educational simulation only. This case is not legal advice and does not predict a real outcome.",
  jurisdictionProfile: {
    profileId: "jurisdiction_fictional_civil_v1",
    name: "Fictional Civil Trial Rules",
    rulesVersion: "rules.v1",
    governingLaw: "Fictional workplace-retaliation and evidence rules created solely for simulation.",
    burdenOfProof: "preponderance",
    permittedObjectionGrounds: [
      "relevance",
      "hearsay",
      "leading",
      "speculation",
      "foundation",
      "asked_and_answered",
      "argumentative",
      "compound",
      "privilege",
    ],
    provenance: [
      authoringProvenance(
        "prov_jurisdiction_rules",
        "The fictional rule profile is authored simulation configuration.",
      ),
    ],
  },
  parties: [
    {
      partyId: "party_rina_shah",
      name: "Rina Shah",
      kind: "person",
      proceduralRole: "claimant",
      simulationSide: "user",
      description: "A product engineer who reported a battery-test safety problem before her termination.",
      counselName: null,
      provenance: [sourceProvenance("prov_party_rina", ["segment_complaint_email"], "Named sender of the complaint email.")],
    },
    {
      partyId: "party_redwood_signal",
      name: "Redwood Signal Systems",
      kind: "organization",
      proceduralRole: "respondent",
      simulationSide: "opposing",
      description: "A fictional electronics company that says performance concerns predated the complaint.",
      counselName: "Alex Chen",
      provenance: [sourceProvenance("prov_party_redwood", ["segment_termination_draft"], "Named employer in the draft memorandum.")],
    },
  ],
  issues: [
    {
      issueId: "issue_retaliatory_causation",
      title: "Retaliatory causation",
      question: "Did Rina's safety complaint materially influence Redwood's final termination decision?",
      burdenPartyId: "party_rina_shah",
      standard: "Rina must prove causation by a preponderance of the jury-considerable record.",
      relatedFactIds: [
        "fact_complaint_sent",
        "fact_draft_created",
        "fact_rationale_revised",
        "fact_manager_accessed_complaint",
        "fact_late_reports",
      ],
      relatedEvidenceIds: [
        "evidence_complaint_email",
        "evidence_draft_metadata",
        "evidence_revision_history",
        "evidence_report_history",
      ],
      provenance: [sourceProvenance("prov_issue_causation", ["segment_complaint_email", "segment_revision_history"], "The packet frames timing and motive as the disputed issue.")],
    },
  ],
  timeline: [
    {
      timelineEventId: "timeline_initial_draft",
      occurredAt: "2026-03-03T09:15:00Z",
      summary: "Theo Morgan created an initial termination draft.",
      relatedFactIds: ["fact_draft_created"],
      relatedEvidenceIds: ["evidence_draft_metadata"],
      witnessIds: ["witness_theo_morgan", "witness_maya_ortiz"],
      provenance: [sourceProvenance("prov_timeline_draft", ["segment_termination_draft"], "Draft metadata timestamp.")],
    },
    {
      timelineEventId: "timeline_safety_complaint",
      occurredAt: "2026-03-10T10:14:00Z",
      summary: "Rina emailed a battery-test safety complaint.",
      relatedFactIds: ["fact_complaint_sent"],
      relatedEvidenceIds: ["evidence_complaint_email"],
      witnessIds: ["witness_rina_shah"],
      provenance: [sourceProvenance("prov_timeline_complaint", ["segment_complaint_email"], "Complaint email timestamp.")],
    },
    {
      timelineEventId: "timeline_complaint_access",
      occurredAt: "2026-03-10T14:02:00Z",
      summary: "Access logs show Theo opened the complaint before revising the termination rationale.",
      relatedFactIds: ["fact_manager_accessed_complaint"],
      relatedEvidenceIds: ["evidence_revision_history"],
      witnessIds: ["witness_theo_morgan", "witness_maya_ortiz"],
      provenance: [sourceProvenance("prov_timeline_access", ["segment_access_log"], "Access-log timestamp.")],
    },
    {
      timelineEventId: "timeline_rationale_revision",
      occurredAt: "2026-03-10T16:38:00Z",
      summary: "The final memorandum added a reference to disruptive escalation.",
      relatedFactIds: ["fact_rationale_revised"],
      relatedEvidenceIds: ["evidence_revision_history"],
      witnessIds: ["witness_theo_morgan", "witness_maya_ortiz"],
      provenance: [sourceProvenance("prov_timeline_revision", ["segment_revision_history"], "Revision-history timestamp.")],
    },
  ],
  facts: [
    {
      factId: "fact_complaint_sent",
      proposition: "Rina sent a battery-test safety complaint at 10:14 AM on March 10.",
      classification: "authoring_truth",
      initialStatus: "verified",
      visibility: "public",
      assertedByPartyIds: ["party_rina_shah"],
      relatedIssueIds: ["issue_retaliatory_causation"],
      relatedEvidenceIds: ["evidence_complaint_email"],
      witnessIds: ["witness_rina_shah"],
      provenance: [sourceProvenance("prov_fact_complaint", ["segment_complaint_email"], "Directly stated in the complaint email.")],
    },
    {
      factId: "fact_draft_created",
      proposition: "Theo created an initial termination draft seven days before the safety complaint.",
      classification: "authoring_truth",
      initialStatus: "verified",
      visibility: "public",
      assertedByPartyIds: ["party_redwood_signal"],
      relatedIssueIds: ["issue_retaliatory_causation"],
      relatedEvidenceIds: ["evidence_draft_metadata"],
      witnessIds: ["witness_theo_morgan", "witness_maya_ortiz"],
      provenance: [sourceProvenance("prov_fact_draft", ["segment_termination_draft"], "Directly supported by document metadata.")],
    },
    {
      factId: "fact_rationale_revised",
      proposition: "The final memorandum added disruptive-escalation language after the complaint.",
      classification: "authoring_truth",
      initialStatus: "verified",
      visibility: "public",
      assertedByPartyIds: ["party_rina_shah"],
      relatedIssueIds: ["issue_retaliatory_causation"],
      relatedEvidenceIds: ["evidence_revision_history"],
      witnessIds: ["witness_theo_morgan", "witness_maya_ortiz"],
      provenance: [sourceProvenance("prov_fact_revision", ["segment_revision_history"], "Directly supported by revision history.")],
    },
    {
      factId: "fact_manager_accessed_complaint",
      proposition: "Theo accessed Rina's complaint before editing the termination memorandum.",
      classification: "authoring_truth",
      initialStatus: "hidden",
      visibility: "restricted",
      assertedByPartyIds: [],
      relatedIssueIds: ["issue_retaliatory_causation"],
      relatedEvidenceIds: ["evidence_revision_history"],
      witnessIds: ["witness_theo_morgan", "witness_maya_ortiz"],
      provenance: [sourceProvenance("prov_fact_access", ["segment_access_log"], "Directly supported by access logs.")],
    },
    {
      factId: "fact_late_reports",
      proposition: "Redwood alleges that Rina submitted two monthly reports late.",
      classification: "party_allegation",
      initialStatus: "proposed",
      visibility: "public",
      assertedByPartyIds: ["party_redwood_signal"],
      relatedIssueIds: ["issue_retaliatory_causation"],
      relatedEvidenceIds: ["evidence_report_history"],
      witnessIds: ["witness_rina_shah", "witness_theo_morgan"],
      provenance: [sourceProvenance("prov_fact_reports", ["segment_report_history"], "The report-history excerpt records two late submissions.", 0.95)],
    },
  ],
  evidence: [
    {
      evidenceId: "evidence_complaint_email",
      name: "Safety complaint email",
      description: "Rina's timestamped email reporting a battery-test interlock problem.",
      kind: "document",
      initialStatus: "indexed",
      authoringAdmissibility: "likely_admissible",
      offeredByPartyIds: ["party_rina_shah"],
      relatedFactIds: ["fact_complaint_sent"],
      relatedIssueIds: ["issue_retaliatory_causation"],
      custodianWitnessIds: ["witness_rina_shah"],
      authenticatingWitnessIds: ["witness_rina_shah"],
      provenance: [sourceProvenance("prov_evidence_complaint", ["segment_complaint_email"], "Packet source segment.")],
    },
    {
      evidenceId: "evidence_draft_metadata",
      name: "Initial termination draft metadata",
      description: "Metadata showing the initial draft's creation time and author.",
      kind: "digital",
      initialStatus: "indexed",
      authoringAdmissibility: "likely_admissible",
      offeredByPartyIds: ["party_redwood_signal"],
      relatedFactIds: ["fact_draft_created"],
      relatedIssueIds: ["issue_retaliatory_causation"],
      custodianWitnessIds: ["witness_theo_morgan", "witness_maya_ortiz"],
      authenticatingWitnessIds: ["witness_maya_ortiz"],
      provenance: [sourceProvenance("prov_evidence_draft", ["segment_termination_draft"], "Packet source segment.")],
    },
    {
      evidenceId: "evidence_revision_history",
      name: "Revision and access history",
      description: "Revision timestamps and access-log entries for the complaint and termination draft.",
      kind: "digital",
      initialStatus: "indexed",
      authoringAdmissibility: "undetermined",
      offeredByPartyIds: ["party_rina_shah"],
      relatedFactIds: ["fact_rationale_revised", "fact_manager_accessed_complaint"],
      relatedIssueIds: ["issue_retaliatory_causation"],
      custodianWitnessIds: ["witness_maya_ortiz"],
      authenticatingWitnessIds: ["witness_maya_ortiz"],
      provenance: [sourceProvenance("prov_evidence_revision", ["segment_revision_history", "segment_access_log"], "Packet source segments.")],
    },
    {
      evidenceId: "evidence_report_history",
      name: "Monthly report history",
      description: "A report-history export showing two submissions after internal due dates.",
      kind: "digital",
      initialStatus: "indexed",
      authoringAdmissibility: "undetermined",
      offeredByPartyIds: ["party_redwood_signal"],
      relatedFactIds: ["fact_late_reports"],
      relatedIssueIds: ["issue_retaliatory_causation"],
      custodianWitnessIds: ["witness_theo_morgan"],
      authenticatingWitnessIds: ["witness_theo_morgan", "witness_maya_ortiz"],
      provenance: [sourceProvenance("prov_evidence_reports", ["segment_report_history"], "Packet source segment.", 0.95)],
    },
  ],
  witnesses: [
    {
      witnessId: "witness_rina_shah",
      name: "Rina Shah",
      kind: "fact",
      role: "Claimant and product engineer",
      alignedPartyId: "party_rina_shah",
      callableByPartyIds: ["party_rina_shah", "party_redwood_signal"],
      summary: "Rina can testify about her complaint, work history, and communications she personally sent or received.",
      emotionalBaseline: "confident",
      knowledgeBoundary: {
        knownFactIds: ["fact_complaint_sent", "fact_late_reports"],
        perceivedFactIds: ["fact_complaint_sent", "fact_late_reports"],
        seenEvidenceIds: ["evidence_complaint_email", "evidence_report_history"],
        availablePriorStatementIds: ["statement_rina_interview"],
        unknownFactIds: ["fact_draft_created", "fact_rationale_revised", "fact_manager_accessed_complaint"],
        allowedTopics: ["Her complaint", "Her report submissions", "Communications she personally observed"],
        forbiddenTopics: ["Theo's private intent", "Unseen access logs", "Legal conclusions"],
      },
      priorStatements: [
        {
          priorStatementId: "statement_rina_interview",
          madeAt: "2026-03-18T11:00:00Z",
          kind: "interview",
          text: "I sent the safety complaint and believed my reports were substantially complete.",
          relatedFactIds: ["fact_complaint_sent", "fact_late_reports"],
          relatedEvidenceIds: ["evidence_complaint_email", "evidence_report_history"],
          provenance: [sourceProvenance("prov_statement_rina", ["segment_complaint_email", "segment_report_history"], "Compiled from Rina's packet interview and referenced records.", 0.9)],
        },
      ],
      provenance: [sourceProvenance("prov_witness_rina", ["segment_complaint_email"], "Identified by the complaint and interview materials.")],
    },
    {
      witnessId: "witness_theo_morgan",
      name: "Theo Morgan",
      kind: "fact",
      role: "Engineering manager and termination-draft author",
      alignedPartyId: "party_redwood_signal",
      callableByPartyIds: ["party_rina_shah", "party_redwood_signal"],
      summary: "Theo can testify about the draft, performance rationale, and edits he personally made.",
      emotionalBaseline: "defensive",
      knowledgeBoundary: {
        knownFactIds: [
          "fact_complaint_sent",
          "fact_draft_created",
          "fact_rationale_revised",
          "fact_manager_accessed_complaint",
          "fact_late_reports",
        ],
        perceivedFactIds: [
          "fact_complaint_sent",
          "fact_draft_created",
          "fact_rationale_revised",
          "fact_manager_accessed_complaint",
        ],
        seenEvidenceIds: ["evidence_draft_metadata", "evidence_revision_history", "evidence_report_history"],
        availablePriorStatementIds: ["statement_theo_email"],
        unknownFactIds: [],
        allowedTopics: ["Documents he created", "Records he reviewed", "His own decision process"],
        forbiddenTopics: ["Rina's uncommunicated beliefs", "Maya's private analysis", "Legal conclusions"],
      },
      priorStatements: [
        {
          priorStatementId: "statement_theo_email",
          madeAt: "2026-03-12T08:20:00Z",
          kind: "email",
          text: "The termination decision was complete before I learned of any safety complaint.",
          relatedFactIds: ["fact_draft_created", "fact_manager_accessed_complaint"],
          relatedEvidenceIds: ["evidence_draft_metadata", "evidence_revision_history"],
          provenance: [sourceProvenance("prov_statement_theo", ["segment_manager_email"], "Direct quotation from Theo's email.")],
        },
      ],
      provenance: [sourceProvenance("prov_witness_theo", ["segment_termination_draft"], "Named author in draft metadata.")],
    },
    {
      witnessId: "witness_maya_ortiz",
      name: "Maya Ortiz",
      kind: "expert",
      role: "Independent digital-records examiner",
      alignedPartyId: null,
      callableByPartyIds: ["party_rina_shah", "party_redwood_signal"],
      summary: "Maya can authenticate metadata and explain access and revision timestamps without opining on motive.",
      emotionalBaseline: "neutral",
      knowledgeBoundary: {
        knownFactIds: ["fact_draft_created", "fact_rationale_revised", "fact_manager_accessed_complaint"],
        perceivedFactIds: [],
        seenEvidenceIds: ["evidence_draft_metadata", "evidence_revision_history", "evidence_report_history"],
        availablePriorStatementIds: ["statement_maya_report"],
        unknownFactIds: ["fact_complaint_sent", "fact_late_reports"],
        allowedTopics: ["Metadata methodology", "Access timestamps", "Revision timestamps"],
        forbiddenTopics: ["Either party's motive", "Legal causation", "Facts outside the examined records"],
      },
      priorStatements: [
        {
          priorStatementId: "statement_maya_report",
          madeAt: "2026-03-20T15:45:00Z",
          kind: "report",
          text: "The access log precedes the disruptive-escalation edit by two hours and thirty-six minutes.",
          relatedFactIds: ["fact_rationale_revised", "fact_manager_accessed_complaint"],
          relatedEvidenceIds: ["evidence_revision_history"],
          provenance: [sourceProvenance("prov_statement_maya", ["segment_access_log", "segment_revision_history"], "Direct conclusion in the examiner report.")],
        },
      ],
      provenance: [sourceProvenance("prov_witness_maya", ["segment_access_log"], "Named examiner in the records report.")],
    },
  ],
  contradictions: [
    {
      contradictionId: "contradiction_access_before_edit",
      summary: "Theo's email denies pre-decision knowledge, while the access log records complaint access before his final edit.",
      left: { kind: "prior_statement", priorStatementId: "statement_theo_email" },
      right: { kind: "fact", factId: "fact_manager_accessed_complaint" },
      witnessIds: ["witness_theo_morgan", "witness_maya_ortiz"],
      relatedIssueIds: ["issue_retaliatory_causation"],
      severity: "decisive",
      provenance: [sourceProvenance("prov_contradiction_access", ["segment_manager_email", "segment_access_log"], "The source records conflict on knowledge timing.")],
    },
  ],
  settlement: {
    enabled: true,
    currency: "USD",
    participants: [
      {
        partyId: "party_rina_shah",
        minimumAuthority: 40_000,
        maximumAuthority: 150_000,
        reservationValue: 60_000,
        targetValue: 110_000,
        confidentialPriorities: ["A neutral reference", "A safety-process review"],
        permittedNonMonetaryTerms: ["Neutral reference", "Written safety review"],
      },
      {
        partyId: "party_redwood_signal",
        minimumAuthority: 0,
        maximumAuthority: 120_000,
        reservationValue: 90_000,
        targetValue: 50_000,
        confidentialPriorities: ["No admission of liability", "Confidential resolution"],
        permittedNonMonetaryTerms: ["Neutral reference", "Confidentiality"],
      },
    ],
    opensAtPhase: "pretrial",
    expiresAfterEventCount: 12,
    allowCounteroffers: true,
    provenance: [authoringProvenance("prov_settlement_config", "Private settlement parameters are authored simulation controls.")],
  },
  juryInstructions: [
    {
      instructionId: "instruction_retaliation_causation",
      title: "Retaliatory causation",
      text: "Decide whether the complaint more likely than not materially influenced the final termination decision. Timing alone is not conclusive.",
      relatedIssueIds: ["issue_retaliatory_causation"],
      requiredFactIds: ["fact_complaint_sent", "fact_draft_created", "fact_rationale_revised"],
      relatedEvidenceIds: ["evidence_complaint_email", "evidence_draft_metadata", "evidence_revision_history"],
      provenance: [authoringProvenance("prov_instruction_causation", "The instruction is authored for the fictional rule profile.")],
    },
  ],
  sourceSegments: [
    {
      sourceSegmentId: "segment_complaint_email",
      sourceId: "source_case_packet",
      documentName: "complaint-email.txt",
      mimeType: "text/plain",
      locator: { kind: "text", startOffset: 0, endOffset: 420 },
      excerpt: "At 10:14 AM, Rina Shah reported a disabled battery-test interlock.",
      sha256: "1111111111111111111111111111111111111111111111111111111111111111",
    },
    {
      sourceSegmentId: "segment_termination_draft",
      sourceId: "source_case_packet",
      documentName: "termination-draft.md",
      mimeType: "text/markdown",
      locator: { kind: "text", startOffset: 421, endOffset: 920 },
      excerpt: "Document metadata: created March 3 at 9:15 AM by Theo Morgan.",
      sha256: "2222222222222222222222222222222222222222222222222222222222222222",
    },
    {
      sourceSegmentId: "segment_revision_history",
      sourceId: "source_case_packet",
      documentName: "revision-history.txt",
      mimeType: "text/plain",
      locator: { kind: "text", startOffset: 921, endOffset: 1_420 },
      excerpt: "March 10, 4:38 PM: added disruptive-escalation language.",
      sha256: "3333333333333333333333333333333333333333333333333333333333333333",
    },
    {
      sourceSegmentId: "segment_access_log",
      sourceId: "source_case_packet",
      documentName: "access-log.txt",
      mimeType: "text/plain",
      locator: { kind: "text", startOffset: 1_421, endOffset: 1_860 },
      excerpt: "March 10, 2:02 PM: Theo Morgan opened complaint-email.txt.",
      sha256: "4444444444444444444444444444444444444444444444444444444444444444",
    },
    {
      sourceSegmentId: "segment_report_history",
      sourceId: "source_case_packet",
      documentName: "report-history.csv",
      mimeType: "text/csv",
      locator: { kind: "text", startOffset: 1_861, endOffset: 2_240 },
      excerpt: "Two monthly reports were logged after their internal due dates.",
      sha256: "5555555555555555555555555555555555555555555555555555555555555555",
    },
    {
      sourceSegmentId: "segment_manager_email",
      sourceId: "source_case_packet",
      documentName: "manager-email.txt",
      mimeType: "text/plain",
      locator: { kind: "text", startOffset: 2_241, endOffset: 2_620 },
      excerpt: "The termination decision was complete before I learned of any safety complaint.",
      sha256: "6666666666666666666666666666666666666666666666666666666666666666",
    },
  ],
  compilerMetadata: {
    method: "seeded",
    model: null,
    requestId: null,
    promptVersion: "case-compiler.seeded.v1",
    compiledAt: "2026-07-18T12:00:00Z",
    sourceContentHash: "abcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcd",
    sourceSegmentCount: 6,
    warnings: [],
    uncertainties: [
      {
        uncertaintyId: "uncertainty_report_context",
        description: "The packet does not establish whether the internal report due dates were communicated consistently.",
        relatedFactIds: ["fact_late_reports"],
        relatedEvidenceIds: ["evidence_report_history"],
        relatedWitnessIds: ["witness_rina_shah", "witness_theo_morgan"],
        sourceSegmentIds: ["segment_report_history"],
      },
    ],
  },
} satisfies CaseGraphV1;

export const THREE_WITNESS_CASE_GRAPH_V1_FIXTURE = parseCaseGraphV1(rawThreeWitnessFixture);

export function createThreeWitnessCaseGraphV1Fixture(): CaseGraphV1 {
  return structuredClone(THREE_WITNESS_CASE_GRAPH_V1_FIXTURE);
}
